**Numpy - Numerical python**

> Adventages of Numpy Arrays

*   Allows several Mathematical Operations
*   faster operations



In [1]:
import numpy as np

**List vs Numpy - Time Taken**

In [2]:
from time import process_time

In [3]:
#time taken by the list

In [13]:
py_list = [i for i in range(10000)]

start_time = process_time()

py_list = [i+5 for i in py_list]

end_time = process_time()

print(end_time - start_time)

0.0015181310000000892


In [14]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array = np_array+5

end_time = process_time()

print(end_time - start_time)

0.001082807999999602


**Numpy arrays**

In [15]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [16]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [17]:
#Creating a one dimensional array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [18]:
a.shape

(5,)

In [20]:
#creating a two dimensional array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
b.shape

(2, 4)

In [22]:
#creating three dimensional array
c = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
c.shape

(3, 3)

In [24]:
d = np.array(([(1,2,3,4),(5,6,7,8)]),dtype=float)
print(d)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


**Initial placeholders in numpy arrays**

In [25]:
#creating a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
#creating a numpy array of zeros
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
# array of particular one
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [28]:
# Creating an Identity Matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
#Create an Numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.91678964 0.31595073 0.27075131 0.1294174 ]
 [0.40880905 0.50660438 0.5344696  0.06676284]
 [0.72520648 0.6143945  0.0712532  0.92936867]]


In [33]:
#Create an Numpy array with random intrgers values
b = np.random.randint(10,100,(3,5))
print(b)

[[83 83 77 64 66]
 [54 70 79 92 21]
 [95 67 24 83 17]]


In [34]:
# array of evenly spaced values
e = np.linspace(10,30,5)
print(e)

[10. 15. 20. 25. 30.]


In [39]:
# array of evenly spaced values --> specifying the step
f = np.arange(10,30,5)
print(f)

[10 15 20 25]


In [40]:
#convert a list to numpy array
list2 = [1,2,3,4,5]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

**Analysing a Numpy array**

In [52]:
c = np.random.randint(10,90,(5,5))
print(c)

[[64 75 62 15 39]
 [16 43 87 50 33]
 [31 30 81 42 39]
 [57 81 87 81 54]
 [64 54 11 30 17]]


In [53]:
#array dimension
print(c.shape)

(5, 5)


In [51]:
#array dimension
print(c.ndim)

2


In [54]:
# number of elements in an array
print(c.size)

25


In [55]:
#checking the data types of the value in the array
print(c.dtype)

int64


**Mathematical operations on a np array**

In [56]:
list1 = [1,2,3,4,5]
list2 = [5,6,7,8,9]
print(list1+list2)

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]


In [57]:
a = np.random.randint(0,10,(3,3))
print(a)

[[2 2 6]
 [3 2 8]
 [6 3 0]]


In [59]:
b = np.random.randint(10,20,(3,3))
print(b)

[[18 10 15]
 [16 10 16]
 [16 13 19]]


In [61]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[20 12 21]
 [19 12 24]
 [22 16 19]]
[[-16  -8  -9]
 [-13  -8  -8]
 [-10 -10 -19]]
[[ 36  20  90]
 [ 48  20 128]
 [ 96  39   0]]
[[0.11111111 0.2        0.4       ]
 [0.1875     0.2        0.5       ]
 [0.375      0.23076923 0.        ]]


In [62]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [64]:
print(a)
print(b)

[[8 8 5]
 [7 8 4]
 [8 6 4]]
[[17 14 13]
 [14 10 13]
 [15 19 17]]


In [65]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[25 22 18]
 [21 18 17]
 [23 25 21]]
[[ -9  -6  -8]
 [ -7  -2  -9]
 [ -7 -13 -13]]
[[136 112  65]
 [ 98  80  52]
 [120 114  68]]
[[0.47058824 0.57142857 0.38461538]
 [0.5        0.8        0.30769231]
 [0.53333333 0.31578947 0.23529412]]


In [67]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 0 8]
 [9 1 3]]
(2, 3)


In [68]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 9]
 [0 1]
 [8 3]]
(3, 2)


In [69]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[9 9]
 [0 1]
 [8 3]]
(3, 2)


In [71]:
#reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 7 0]
 [3 8 1]]
(2, 3)


In [72]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[9 7]
 [0 3]
 [8 1]]
(3, 2)
